# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'Traces' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'YandexMapsMobile', '4.5.1-full'

  # Pods for Traces

end
